// This file is @generated by prost-build.
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Packet {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<PacketHeader>,
    #[prost(message, optional, tag = "2")]
    pub payload: ::core::option::Option<PacketPayload>,
    #[prost(message, optional, tag = "3")]
    pub checksum: ::core::option::Option<PacketChecksum>,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<PacketTimestamp>,
    #[prost(message, optional, tag = "5")]
    pub source: ::core::option::Option<PacketSource>,
    #[prost(message, optional, tag = "6")]
    pub destination: ::core::option::Option<PacketDestination>,
    #[prost(message, optional, tag = "7")]
    pub protocol: ::core::option::Option<PacketProtocol>,
    #[prost(message, optional, tag = "8")]
    pub flags: ::core::option::Option<PacketFlags>,
    #[prost(message, optional, tag = "9")]
    pub version: ::core::option::Option<PacketVersion>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PacketHeader {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(uint32, tag = "2")]
    pub length: u32,
    #[prost(uint32, tag = "3")]
    pub checksum: u32,
    #[prost(uint32, tag = "4")]
    pub version: u32,
    #[prost(uint32, tag = "5")]
    pub flags: u32,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketPayload {
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub size: u32,
    #[prost(string, tag = "4")]
    pub encoding: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketChecksum {
    #[prost(uint32, tag = "1")]
    pub algorithm: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub length: u32,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PacketTimestamp {
    #[prost(uint32, tag = "1")]
    pub seconds: u32,
    #[prost(uint32, tag = "2")]
    pub nanoseconds: u32,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketSource {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
    #[prost(string, tag = "3")]
    pub mac: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketDestination {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub port: u32,
    #[prost(string, tag = "3")]
    pub mac: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketProtocol {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub version: u32,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PacketFlags {
    #[prost(bool, tag = "1")]
    pub is_fragmented: bool,
    #[prost(bool, tag = "2")]
    pub is_encrypted: bool,
    #[prost(bool, tag = "3")]
    pub is_compressed: bool,
    #[prost(bool, tag = "4")]
    pub is_signed: bool,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketVersion {
    #[prost(uint32, tag = "1")]
    pub major: u32,
    #[prost(uint32, tag = "2")]
    pub minor: u32,
    #[prost(uint32, tag = "3")]
    pub patch: u32,
    #[prost(string, tag = "4")]
    pub build: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketError {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub details: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketStatus {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub details: ::prost::alloc::string::String,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketResponse {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<PacketError>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<PacketStatus>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketRequest {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub params: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<PacketError>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<PacketStatus>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketAck {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<PacketError>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<PacketStatus>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketNack {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<PacketError>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<PacketStatus>,
}
#[derive(::serde::Serialize, ::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PacketPing {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub error: ::core::option::Option<PacketError>,
    #[prost(message, optional, tag = "5")]
    pub status: ::core::option::Option<PacketStatus>,
}
